Repository megschuetz/fitlit, pull requests merged in 2022-06, with the labels that each got.

#81 Refactor/refactor activity class
  src/Activity.js
  test/Activity-test.js
Labels: enhancement, refactor

#87 Feature/create html boxes
  dist/index.html
  src/scripts.js
Labels: enhancement

#89 Feature/connect user avgs to dom
  src/Activity.js
  src/scripts.js
  test/Activity-test.js
Labels: bug, enhancement

#92 start post requests
  src/scripts.js
Labels: enhancement

#102 Feat/disable buttons
  dist/index.html
  src/css/styles.css
  src/scripts.js
Labels: enhancement

#103 Refactor/event handlers
  dist/index.html
  src/scripts.js
Labels: enhancement
